# Generated by Django 2.0.3 on 2018-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WavIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('albom', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('tag', models.IntegerField(blank=True)),
                ('data', models.CharField(blank=True, max_length=3000)),
                ('dist', models.IntegerField(blank=True)),
                ('yandex_au_url', models.CharField(blank=True, max_length=3000)),
            ],
        ),
    ]
