# Generated by Django 2.0.3 on 2018-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wav_io', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WavIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.IntegerField()),
                ('data', models.CharField(max_length=300)),
                ('dist', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='waw_io',
        ),
    ]
